# This is a basic workflow to help you get started with Actions

name: snyk_multistage

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # build the container image for the application
      - name: docker build
        run: docker build -t myapp:build -f Dockerfile.build .
        
      # build a new container image which includes snyk test from prevous builder image
      - name: docker build with snyk
        run: docker build -t myapp:build_snyk -f Dockerfile.build_snyk .

      # invoke snyk test from within the built container image
      - name: docker run
        run: docker run --rm -e SNYK_TOKEN=${{ secrets.SNYK_TOKEN }} myapp:build_snyk snyk test
      
